"""Kaleidoscope"""
load("@rules_cc//cc/toolchains:toolchain.bzl", "cc_toolchain")
load("@rules_cc//cc/toolchains:tool_map.bzl", "cc_tool_map")
load("@rules_cc//cc/toolchains:tool.bzl", "cc_tool")
load("@rules_cc//cc/toolchains:args.bzl", "cc_args")
# package(default_visibility = ["//visibility:private"])

cc_args(
    name = "kaleidoscope_sysroot",
    actions = [
        "@rules_cc//cc/toolchains/actions:compile_actions",
    ],
    args = ["-no-canonical-prefixes","--sysroot=/opt/kaleidoscope"],
    visibility = ["//visibility:public"],
)

    # args = ["-ffreestanding", "-O0", "-g", "-Wall",  "-Wextra", "-fuse-ld=lld", "-nostdlib"],
    # args = ["-no-canonical-prefixes"],
cc_args(
    name = "rv64i_zicsr",
    args = ["-march=rv64i", "-mabi=lp64"],
    actions = [
        "@rules_cc//cc/toolchains/actions:compile_actions",
        "@rules_cc//cc/toolchains/actions:link_actions",
    ],
)

# cc_make_variable(
#     name = "example_variable",
#     value = "-DEXAMPLE=1",
#     variable_name = "EXAMPLE_SUBSTITUTION",
# )

cc_toolchain(
    name = "kaleidoscope_toolchain_clang",
    args = [":kaleidoscope_sysroot"],
    # args = [":rv64i_zicsr"],
    # args = select({
    #     "@platforms//os:linux": [
    #         "//toolchains/clang/args:linux_sysroot",
    #     ],
    #     "//conditions:default": [],
    # }) + [
    #     "//toolchains/args:no_absolute_paths_for_builtins",
    #     "//toolchains/args:warnings",
    #     "//toolchains/args:target",
    # ],
    enabled_features = ["@rules_cc//cc/toolchains/args:experimental_replace_legacy_action_config_features"],
    known_features = ["@rules_cc//cc/toolchains/args:experimental_replace_legacy_action_config_features"],
    # make_variables = [":example_variable"],
    tool_map = ":tool_map",
)

toolchain(
    name = "kaleidoscope_toolchain",
    # visibility = ["//visibility:public"],
    toolchain = ":kaleidoscope_toolchain_clang",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
    target_compatible_with = ["@platforms//cpu:riscv64"],
)

cc_tool_map(
    name = "tool_map",
    tools = {
        "@rules_cc//cc/toolchains/actions:assembly_actions": ":clang",
        "@rules_cc//cc/toolchains/actions:c_compile": ":clang",
        "@rules_cc//cc/toolchains/actions:cpp_compile_actions": ":clang++",
        "@rules_cc//cc/toolchains/actions:link_actions": ":lld",
        # "@rules_cc//cc/toolchains/actions:ar_actions": ":llvm-ar",
        # "@rules_cc//cc/toolchains/actions:objcopy_embed_data": ":llvm-objcopy",
        # "@rules_cc//cc/toolchains/actions:strip": ":llvm-strip",
    }
    # visibility = ["//visibility:public"],
)

cc_tool(
    name = "clang",
    src = "@kaleidoscope//containers:clang",
    # data = [":builtin_headers"],
)

cc_tool(
    name = "clang++",
    src = "@kaleidoscope//containers:clang++",
)

cc_tool(
    name = "lld",
    src = "@kaleidoscope//containers:clang",
)
